In [1]:
import pandas as pd
import numpy as np
import sklearn as sns

In [2]:
df = pd.read_csv("insurance_data.csv")

In [3]:
df

,age,gender,bmi,children,smoker,region,charges
0,19,female,27.900,0,yes,southwest,16884.92400
1,18,male,33.770,1,no,southeast,1725.55230
2,28,male,33.000,3,no,southeast,4449.46200
3,33,male,22.705,0,no,northwest,21984.47061
4,32,male,28.880,0,no,northwest,3866.85520
...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830
1334,18,female,31.920,0,no,northeast,2205.98080
1335,18,female,36.850,0,no,southeast,1629.83350
1336,21,female,25.800,0,no,southwest,2007.94500


In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   gender    1338 non-null   str    
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   str    
 5   region    1338 non-null   str    
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), str(3)
memory usage: 73.3 KB


In [5]:
df.isnull()

,age,gender,bmi,children,smoker,region,charges
0,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...
1333,False,False,False,False,False,False,False
1334,False,False,False,False,False,False,False
1335,False,False,False,False,False,False,False
1336,False,False,False,False,False,False,False


In [6]:
df.isnull().sum()

age         0
gender      0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [7]:
df.value_counts()

age  gender  bmi     children  smoker  region     charges    
19   male    30.590  0         no      northwest  1639.56310     2
     female  27.900  0         yes     southwest  16884.92400    1
18   male    33.770  1         no      southeast  1725.55230     1
28   male    33.000  3         no      southeast  4449.46200     1
33   male    22.705  0         no      northwest  21984.47061    1
                                                                ..
50   male    30.970  3         no      northwest  10600.54830    1
18   female  31.920  0         no      northeast  2205.98080     1
             36.850  0         no      southeast  1629.83350     1
21   female  25.800  0         no      southwest  2007.94500     1
61   female  29.070  0         yes     northwest  29141.36030    1
Name: count, Length: 1337, dtype: int64

In [8]:
df.duplicated().sum()

np.int64(1)

In [9]:
df.drop_duplicates(inplace=True)

In [10]:
df['gender'].unique()

<StringArray>
['female', 'male']
Length: 2, dtype: str

In [11]:
gender ={
    'female':0, 'male':1
}

In [12]:
df['gender']=df['gender'].map(gender)


In [13]:
df

,age,gender,bmi,children,smoker,region,charges
0,19,0,27.900,0,yes,southwest,16884.92400
1,18,1,33.770,1,no,southeast,1725.55230
2,28,1,33.000,3,no,southeast,4449.46200
3,33,1,22.705,0,no,northwest,21984.47061
4,32,1,28.880,0,no,northwest,3866.85520
...,...,...,...,...,...,...,...
1333,50,1,30.970,3,no,northwest,10600.54830
1334,18,0,31.920,0,no,northeast,2205.98080
1335,18,0,36.850,0,no,southeast,1629.83350
1336,21,0,25.800,0,no,southwest,2007.94500


In [14]:
df['smoker'].unique()

<StringArray>
['yes', 'no']
Length: 2, dtype: str

In [15]:
smoker ={
    'yes':1, 'no':0
}

In [16]:
df['smoker']=df['smoker'].map(smoker)


In [17]:
df

,age,gender,bmi,children,smoker,region,charges
0,19,0,27.900,0,1,southwest,16884.92400
1,18,1,33.770,1,0,southeast,1725.55230
2,28,1,33.000,3,0,southeast,4449.46200
3,33,1,22.705,0,0,northwest,21984.47061
4,32,1,28.880,0,0,northwest,3866.85520
...,...,...,...,...,...,...,...
1333,50,1,30.970,3,0,northwest,10600.54830
1334,18,0,31.920,0,0,northeast,2205.98080
1335,18,0,36.850,0,0,southeast,1629.83350
1336,21,0,25.800,0,0,southwest,2007.94500


In [18]:
df['region'].unique()

<StringArray>
['southwest', 'southeast', 'northwest', 'northeast']
Length: 4, dtype: str

In [19]:
#region ={
    #'southwest':1, 'southeast':2, 'northwest':3, 'northeast':4
#}

In [20]:
#df['region']=df['region'].map(region)


In [21]:
df

,age,gender,bmi,children,smoker,region,charges
0,19,0,27.900,0,1,southwest,16884.92400
1,18,1,33.770,1,0,southeast,1725.55230
2,28,1,33.000,3,0,southeast,4449.46200
3,33,1,22.705,0,0,northwest,21984.47061
4,32,1,28.880,0,0,northwest,3866.85520
...,...,...,...,...,...,...,...
1333,50,1,30.970,3,0,northwest,10600.54830
1334,18,0,31.920,0,0,northeast,2205.98080
1335,18,0,36.850,0,0,southeast,1629.83350
1336,21,0,25.800,0,0,southwest,2007.94500


In [22]:
df.duplicated().sum()

np.int64(0)

In [23]:
x=df.drop(columns=['charges','region'])
y=df['charges']


In [24]:
x

,age,gender,bmi,children,smoker
0,19,0,27.900,0,1
1,18,1,33.770,1,0
2,28,1,33.000,3,0
3,33,1,22.705,0,0
4,32,1,28.880,0,0
...,...,...,...,...,...
1333,50,1,30.970,3,0
1334,18,0,31.920,0,0
1335,18,0,36.850,0,0
1336,21,0,25.800,0,0


In [25]:
y

0       16884.92400
1        1725.55230
2        4449.46200
3       21984.47061
4        3866.85520
           ...     
1333    10600.54830
1334     2205.98080
1335     1629.83350
1336     2007.94500
1337    29141.36030
Name: charges, Length: 1337, dtype: float64

In [26]:
x.duplicated().sum()

np.int64(2)

In [27]:
#x.drop_duplicates(inplace=True)

In [28]:
y.duplicated().sum()

np.int64(0)

In [29]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [30]:
x_train

,age,gender,bmi,children,smoker
1114,23,1,24.510,0,0
968,21,1,25.745,2,0
599,52,0,37.525,2,0
170,63,1,41.470,0,0
275,47,0,26.600,2,0
...,...,...,...,...,...
1096,51,0,34.960,2,1
1131,27,1,45.900,2,0
1295,20,1,22.000,1,0
861,38,0,28.000,3,0


In [31]:
x_test

,age,gender,bmi,children,smoker
900,49,1,22.515,0,0
1064,29,0,25.600,4,0
1256,51,0,36.385,3,0
298,31,1,34.390,3,1
237,31,1,38.390,2,0
...,...,...,...,...,...
534,64,1,40.480,0,0
542,63,0,36.300,0,0
760,22,0,34.580,2,0
1284,61,1,36.300,1,1


In [32]:
y_train

1114     2396.09590
968      3279.86855
599     33471.97189
170     13405.39030
275      9715.84100
           ...     
1096    44641.19740
1131     3693.42800
1295     1964.78000
861      7151.09200
1127     5836.52040
Name: charges, Length: 1069, dtype: float64

In [33]:
y_test

900      8688.85885
1064     5708.86700
1256    11436.73815
298     38746.35510
237      4463.20510
           ...     
534     13831.11520
542     13887.20400
760      3925.75820
1284    47403.88000
1285     8534.67180
Name: charges, Length: 268, dtype: float64

In [34]:
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)

(1069, 5) (268, 5) (1069,) (268,)


In [35]:
x_train, x_test, y_train, y_test = x_train, x_test, y_train, y_test.drop_duplicates()

In [36]:
x

,age,gender,bmi,children,smoker
0,19,0,27.900,0,1
1,18,1,33.770,1,0
2,28,1,33.000,3,0
3,33,1,22.705,0,0
4,32,1,28.880,0,0
...,...,...,...,...,...
1333,50,1,30.970,3,0
1334,18,0,31.920,0,0
1335,18,0,36.850,0,0
1336,21,0,25.800,0,0


In [37]:
df

,age,gender,bmi,children,smoker,region,charges
0,19,0,27.900,0,1,southwest,16884.92400
1,18,1,33.770,1,0,southeast,1725.55230
2,28,1,33.000,3,0,southeast,4449.46200
3,33,1,22.705,0,0,northwest,21984.47061
4,32,1,28.880,0,0,northwest,3866.85520
...,...,...,...,...,...,...,...
1333,50,1,30.970,3,0,northwest,10600.54830
1334,18,0,31.920,0,0,northeast,2205.98080
1335,18,0,36.850,0,0,southeast,1629.83350
1336,21,0,25.800,0,0,southwest,2007.94500


In [38]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()


In [39]:
lr.fit(x_train,y_train)


,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies a different convergence criterion for the `lsqr` solver.`tol` is set as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. This parameter has no effect when fittingon dense data... versionadded:: 1.7",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary ` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False


In [40]:
southwest = lr.predict(x_test)

In [41]:
southwest

array([ 7780.09204548,  5977.83338997, 14215.82300956, 31590.59473466,
        9223.64922442, 13438.43822409, 29841.65667782,  1685.03795715,
       10919.46514725, 11281.04050309, 10418.78669104, 33059.36084168,
       30531.50988264, 17420.0023959 , 10214.90616935,  9749.75223135,
        4298.47335596, 32007.67725019,  3488.96062241,  5583.27330599,
        3845.53703027, 29815.02239719, 15103.39914515, 30646.34708594,
       30908.30211535,  5363.08477297, 35705.172843  , 36714.56751572,
       10928.83748576, 13689.22034633,  5994.25520485, 13015.10761713,
         842.10884744, 12332.40611586, 39769.78804625, 12472.16793437,
        4941.6340669 ,  3962.34504306, 31334.30270026,  9347.27340131,
        6423.31161511, 29743.01929574, 35062.57980736, 11806.50755259,
        7409.90515685,  3638.00400509,  5572.08908023,  9165.34126485,
        4217.22289854,  9367.5521687 ,  6914.22550367, 11443.85328341,
       30801.79761652,  3861.35683277, 11172.20169464, 10108.79403925,
      

In [42]:
x

,age,gender,bmi,children,smoker
0,19,0,27.900,0,1
1,18,1,33.770,1,0
2,28,1,33.000,3,0
3,33,1,22.705,0,0
4,32,1,28.880,0,0
...,...,...,...,...,...
1333,50,1,30.970,3,0
1334,18,0,31.920,0,0
1335,18,0,36.850,0,0
1336,21,0,25.800,0,0


In [43]:
lr.predict([[19,	0,	27.900,	0,	1]])

c:\Users\om sai compurer1\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([25089.26781169])

In [44]:
lr.predict(x_train)

array([ 1913.28139775,  2868.42936746, 14275.33486501, ...,
         936.91190884,  8415.15856955,  9531.89800259], shape=(1069,))

In [45]:
from sklearn.svm import SVR
sv = SVR()

In [46]:
import imblearn
from imblearn.over_sampling import SMOTE

In [47]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

#Apply SMOTE to the training data
sm = SMOTE(random_state=42)


In [48]:
sv.fit(x_train, y_train)

,"kernel kernel: {'linear', 'poly', 'rbf', 'sigmoid', 'precomputed'} or callable, default='rbf'Specifies the kernel type to be used in the algorithm.If none is given, 'rbf' will be used. If a callable is given it isused to precompute the kernel matrix.For an intuitive visualization of different kernel typessee :ref:`sphx_glr_auto_examples_svm_plot_svm_regression.py`",'rbf'
,"degree degree: int, default=3Degree of the polynomial kernel function ('poly').Must be non-negative. Ignored by all other kernels.",3
,"gamma gamma: {'scale', 'auto'} or float, default='scale'Kernel coefficient for 'rbf', 'poly' and 'sigmoid'.- if ``gamma='scale'`` (default) is passed then it uses 1 / (n_features * X.var()) as value of gamma,- if 'auto', uses 1 / n_features- if float, must be non-negative... versionchanged:: 0.22 The default value of ``gamma`` changed from 'auto' to 'scale'.",'scale'
,"coef0 coef0: float, default=0.0Independent term in kernel function.It is only significant in 'poly' and 'sigmoid'.",0.0
,"tol tol: float, default=1e-3Tolerance for stopping criterion.",0.001
,"C C: float, default=1.0Regularization parameter. The strength of the regularization isinversely proportional to C. Must be strictly positive.The penalty is a squared l2. For an intuitive visualization of theeffects of scaling the regularization parameter C, see:ref:`sphx_glr_auto_examples_svm_plot_svm_scale_c.py`.",1.0
,"epsilon epsilon: float, default=0.1Epsilon in the epsilon-SVR model. It specifies the epsilon-tubewithin which no penalty is associated in the training loss functionwith points predicted within a distance epsilon from the actualvalue. Must be non-negative.",0.1
,"shrinking shrinking: bool, default=TrueWhether to use the shrinking heuristic.See the :ref:`User Guide `.",True
,"cache_size cache_size: float, default=200Specify the size of the kernel cache (in MB).",200
,"verbose verbose: bool, default=FalseEnable verbose output. Note that this setting takes advantage of aper-process runtime setting in libsvm that, if enabled, may not workproperly in a multithreaded context.",False
,"max_iter max_iter: int, default=-1Hard limit on iterations within solver, or -1 for no limit.",-1


In [49]:
pred =sv.predict(x_test)
pred

array([9284.70136804, 9153.31174498, 9304.75398383, 9167.10855523,
       9170.26299602, 9291.53080107, 9132.26460727, 9124.54795089,
       9248.42951737, 9288.82724377, 9349.35852994, 9308.43755094,
       9172.19186389, 9352.43387792, 9194.13768871, 9260.16986502,
       9119.77267228, 9198.76431594, 9139.31242356, 9153.05227249,
       9119.8098343 , 9195.34642876, 9291.02999672, 9216.35093044,
       9179.63934438, 9122.93761832, 9243.45474927, 9355.12475809,
       9289.90490894, 9284.23662686, 9164.63279667, 9298.26552957,
       9115.82073123, 9348.06474049, 9317.22470713, 9304.63664288,
       9117.23833368, 9160.35789186, 9308.88135491, 9267.14093131,
       9132.9016745 , 9242.03045669, 9248.81244363, 9304.15858571,
       9262.44810549, 9147.71083781, 9124.1846916 , 9245.9736461 ,
       9147.66752127, 9217.86509542, 9149.64723119, 9223.96520916,
       9244.15983574, 9120.04766368, 9241.24850652, 9253.72020418,
       9302.00287731, 9135.82112805, 9179.80161485, 9231.57946

In [50]:
sv.score(x_test, y_test)

-0.1344441061397712

In [51]:
pred[0:20]

array([9284.70136804, 9153.31174498, 9304.75398383, 9167.10855523,
       9170.26299602, 9291.53080107, 9132.26460727, 9124.54795089,
       9248.42951737, 9288.82724377, 9349.35852994, 9308.43755094,
       9172.19186389, 9352.43387792, 9194.13768871, 9260.16986502,
       9119.77267228, 9198.76431594, 9139.31242356, 9153.05227249])

In [56]:
from sklearn.tree import DecisionTreeRegressor

In [57]:
dtr = DecisionTreeRegressor()
dtr.fit(x_train,y_train)
pred = dtr.predict(x_test)
pred


array([ 9361.3268 ,  4877.98105, 10848.1343 , 44585.45587,  4673.3922 ,
       10269.46   , 37484.4493 ,  2154.361  , 19144.57652, 10702.6424 ,
       13616.3586 , 23065.4207 , 51194.55914, 13470.86   ,  5836.5204 ,
        8516.829  ,  2362.22905, 39774.2763 , 23241.47453,  4040.55825,
        1748.774  , 20296.86345, 10370.91255, 20296.86345, 37079.372  ,
        7418.522  , 42560.4304 , 46130.5265 ,  9910.35985,  9563.029  ,
        3761.292  ,  9386.1613 ,  1837.237  , 12913.9924 , 48549.17835,
        9283.562  ,  4915.05985,  4906.40965, 22412.6485 ,  8823.279  ,
        1633.9618 , 18767.7377 , 41034.2214 ,  9290.1395 ,  9500.57305,
        3732.6251 ,  1634.5734 ,  7727.2532 ,  4337.7352 ,  6986.697  ,
        4922.9159 ,  5438.7491 , 21880.82   ,  1880.487  ,  7160.3303 ,
        8116.26885,  9617.66245,  3208.787  , 51194.55914,  6600.361  ,
       11299.343  ,  5246.047  , 29186.48236,  1708.0014 , 12485.8009 ,
       12094.478  ,  6112.35295, 21774.32215, 17178.6824 , 14418

In [58]:
dtr.get_params()

{'ccp_alpha': 0.0,
 'criterion': 'squared_error',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'random_state': None,
 'splitter': 'best'}

In [59]:
df.to_csv('insurance.csv',index=False)